services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    #profiles:
      #- dev
      #- homolog
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net

  web_app:
    extends:
      file: ./kube-news.compose.yaml
      service: kube_news

volumes:
  postgre_docker_vol:

networks:
  kube_news_net:
    driver: bridge